<?xml version="1.0" standalone="yes"?><!DOCTYPE wcgenrehist [
	<!ELEMENT wcgenrehist (gid, error, gname, genre_wordcount, wordcounts)>
	<!ELEMENT gid (#PCDATA)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT gname (#PCDATA)>
	<!ELEMENT genre_wordcount (#PCDATA)>
	<!ELEMENT wordcounts (wcentry+)>
	<!ELEMENT wcentry (wc, wcdate, max, min, stddev, average, count)>
	<!ELEMENT wc (#PCDATA)>
	<!ELEMENT wcdate (#PCDATA)>
	<!ELEMENT max (#PCDATA)>
	<!ELEMENT min (#PCDATA)>
	<!ELEMENT stddev (#PCDATA)>
	<!ELEMENT average (#PCDATA)>
	<!ELEMENT count (#PCDATA)>
]>
<wcgenrehist>
<gid>5</gid>
<gname>Historical Fiction</gname>
<genre_wordcount>28813857</genre_wordcount>
<wordcounts>
<wcentry>
<wc>111135</wc>
<wcdate>2007-11-01</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>1035255</wc>
<wcdate>2007-11-02</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>2215052</wc>
<wcdate>2007-11-03</wcdate>
<max>17881</max>
<min>9</min>
<stddev>0</stddev>
<average>3281</average>
<count>675</count>
</wcentry>
<wcentry>
<wc>2215052</wc>
<wcdate>2007-11-04</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>3822161</wc>
<wcdate>2007-11-05</wcdate>
<max>32211</max>
<min>0</min>
<stddev>0</stddev>
<average>4893</average>
<count>781</count>
</wcentry>
<wcentry>
<wc>4883202</wc>
<wcdate>2007-11-06</wcdate>
<max>33016</max>
<min>0</min>
<stddev>0</stddev>
<average>5758</average>
<count>848</count>
</wcentry>
<wcentry>
<wc>5964382</wc>
<wcdate>2007-11-07</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>6686</average>
<count>892</count>
</wcentry>
<wcentry>
<wc>6806447</wc>
<wcdate>2007-11-08</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>7342</average>
<count>927</count>
</wcentry>
<wcentry>
<wc>7590598</wc>
<wcdate>2007-11-09</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>7998</average>
<count>949</count>
</wcentry>
<wcentry>
<wc>8468218</wc>
<wcdate>2007-11-10</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>8748</average>
<count>968</count>
</wcentry>
<wcentry>
<wc>9355881</wc>
<wcdate>2007-11-11</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>9566</average>
<count>978</count>
</wcentry>
<wcentry>
<wc>10266500</wc>
<wcdate>2007-11-12</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>10370</average>
<count>990</count>
</wcentry>
<wcentry>
<wc>11111433</wc>
<wcdate>2007-11-13</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>11100</average>
<count>1001</count>
</wcentry>
<wcentry>
<wc>11933931</wc>
<wcdate>2007-11-14</wcdate>
<max>115418</max>
<min>0</min>
<stddev>0</stddev>
<average>11898</average>
<count>1003</count>
</wcentry>
<wcentry>
<wc>12948989</wc>
<wcdate>2007-11-15</wcdate>
<max>117826</max>
<min>0</min>
<stddev>0</stddev>
<average>12732</average>
<count>1017</count>
</wcentry>
<wcentry>
<wc>13758903</wc>
<wcdate>2007-11-16</wcdate>
<max>117826</max>
<min>0</min>
<stddev>0</stddev>
<average>13449</average>
<count>1023</count>
</wcentry>
<wcentry>
<wc>14445427</wc>
<wcdate>2007-11-17</wcdate>
<max>117826</max>
<min>0</min>
<stddev>0</stddev>
<average>14093</average>
<count>1025</count>
</wcentry>
<wcentry>
<wc>15201597</wc>
<wcdate>2007-11-18</wcdate>
<max>117826</max>
<min>0</min>
<stddev>0</stddev>
<average>14816</average>
<count>1026</count>
</wcentry>
<wcentry>
<wc>16099135</wc>
<wcdate>2007-11-19</wcdate>
<max>129022</max>
<min>0</min>
<stddev>0</stddev>
<average>15584</average>
<count>1033</count>
</wcentry>
<wcentry>
<wc>17002665</wc>
<wcdate>2007-11-20</wcdate>
<max>129022</max>
<min>0</min>
<stddev>0</stddev>
<average>16411</average>
<count>1036</count>
</wcentry>
<wcentry>
<wc>17789749</wc>
<wcdate>2007-11-21</wcdate>
<max>137542</max>
<min>0</min>
<stddev>0</stddev>
<average>17121</average>
<count>1039</count>
</wcentry>
<wcentry>
<wc>18675088</wc>
<wcdate>2007-11-22</wcdate>
<max>137542</max>
<min>0</min>
<stddev>0</stddev>
<average>17888</average>
<count>1044</count>
</wcentry>
<wcentry>
<wc>19345211</wc>
<wcdate>2007-11-23</wcdate>
<max>140024</max>
<min>0</min>
<stddev>0</stddev>
<average>18476</average>
<count>1047</count>
</wcentry>
<wcentry>
<wc>19985700</wc>
<wcdate>2007-11-24</wcdate>
<max>151002</max>
<min>0</min>
<stddev>0</stddev>
<average>19034</average>
<count>1050</count>
</wcentry>
<wcentry>
<wc>20986533</wc>
<wcdate>2007-11-25</wcdate>
<max>151002</max>
<min>0</min>
<stddev>0</stddev>
<average>19892</average>
<count>1055</count>
</wcentry>
<wcentry>
<wc>22270955</wc>
<wcdate>2007-11-26</wcdate>
<max>157393</max>
<min>0</min>
<stddev>0</stddev>
<average>21069</average>
<count>1057</count>
</wcentry>
<wcentry>
<wc>23350491</wc>
<wcdate>2007-11-27</wcdate>
<max>157393</max>
<min>0</min>
<stddev>0</stddev>
<average>22049</average>
<count>1059</count>
</wcentry>
<wcentry>
<wc>24506882</wc>
<wcdate>2007-11-28</wcdate>
<max>172920</max>
<min>0</min>
<stddev>0</stddev>
<average>23076</average>
<count>1062</count>
</wcentry>
<wcentry>
<wc>25586637</wc>
<wcdate>2007-11-29</wcdate>
<max>172920</max>
<min>0</min>
<stddev>0</stddev>
<average>24002</average>
<count>1066</count>
</wcentry>
<wcentry>
<wc>28813857</wc>
<wcdate>2007-11-30</wcdate>
<max>200325</max>
<min>0</min>
<stddev>0</stddev>
<average>26556</average>
<count>1085</count>
</wcentry>
</wordcounts>
</wcgenrehist>
