<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE wchistory [
	<!ELEMENT wchistory (uid, error, uname, user_wordcount, wordcounts)>
	<!ELEMENT uid (#PCDATA)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT uname (#PCDATA)>
	<!ELEMENT user_wordcount (#PCDATA)>
	<!ELEMENT wordcounts (wcentry+)>
	<!ELEMENT wcentry (wc,wcdate)>
	<!ELEMENT wc (#PCDATA)>
	<!ELEMENT wcdate (#PCDATA)>
]>
<wchistory>
<uid>30837</uid>
<uname>NewMexicoKid</uname>
<user_wordcount>57222</user_wordcount>
<wordcounts>
<wcentry>
<wc>2063</wc>
<wcdate>2007-11-01</wcdate>
</wcentry>
<wcentry>
<wc>3449</wc>
<wcdate>2007-11-02</wcdate>
</wcentry>
<wcentry>
<wc>4701</wc>
<wcdate>2007-11-03</wcdate>
</wcentry>
<wcentry>
<wc>8140</wc>
<wcdate>2007-11-04</wcdate>
</wcentry>
<wcentry>
<wc>8140</wc>
<wcdate>2007-11-05</wcdate>
</wcentry>
<wcentry>
<wc>12561</wc>
<wcdate>2007-11-06</wcdate>
</wcentry>
<wcentry>
<wc>14056</wc>
<wcdate>2007-11-07</wcdate>
</wcentry>
<wcentry>
<wc>14056</wc>
<wcdate>2007-11-08</wcdate>
</wcentry>
<wcentry>
<wc>14056</wc>
<wcdate>2007-11-09</wcdate>
</wcentry>
<wcentry>
<wc>17049</wc>
<wcdate>2007-11-10</wcdate>
</wcentry>
<wcentry>
<wc>19385</wc>
<wcdate>2007-11-11</wcdate>
</wcentry>
<wcentry>
<wc>20036</wc>
<wcdate>2007-11-12</wcdate>
</wcentry>
<wcentry>
<wc>20036</wc>
<wcdate>2007-11-13</wcdate>
</wcentry>
<wcentry>
<wc>21226</wc>
<wcdate>2007-11-14</wcdate>
</wcentry>
<wcentry>
<wc>22225</wc>
<wcdate>2007-11-15</wcdate>
</wcentry>
<wcentry>
<wc>24361</wc>
<wcdate>2007-11-16</wcdate>
</wcentry>
<wcentry>
<wc>27531</wc>
<wcdate>2007-11-17</wcdate>
</wcentry>
<wcentry>
<wc>30578</wc>
<wcdate>2007-11-18</wcdate>
</wcentry>
<wcentry>
<wc>32028</wc>
<wcdate>2007-11-19</wcdate>
</wcentry>
<wcentry>
<wc>32028</wc>
<wcdate>2007-11-20</wcdate>
</wcentry>
<wcentry>
<wc>33386</wc>
<wcdate>2007-11-21</wcdate>
</wcentry>
<wcentry>
<wc>36690</wc>
<wcdate>2007-11-22</wcdate>
</wcentry>
<wcentry>
<wc>36690</wc>
<wcdate>2007-11-23</wcdate>
</wcentry>
<wcentry>
<wc>43001</wc>
<wcdate>2007-11-24</wcdate>
</wcentry>
<wcentry>
<wc>49137</wc>
<wcdate>2007-11-25</wcdate>
</wcentry>
<wcentry>
<wc>50092</wc>
<wcdate>2007-11-26</wcdate>
</wcentry>
<wcentry>
<wc>50092</wc>
<wcdate>2007-11-27</wcdate>
</wcentry>
<wcentry>
<wc>50092</wc>
<wcdate>2007-11-28</wcdate>
</wcentry>
<wcentry>
<wc>50644</wc>
<wcdate>2007-11-29</wcdate>
</wcentry>
<wcentry>
<wc>57222</wc>
<wcdate>2007-11-30</wcdate>
</wcentry>
</wordcounts>
</wchistory>