<?xml version="1.0" standalone="yes"?><!DOCTYPE wcregionhist [
	<!ELEMENT wcregionhist (rid, error, rname, region_wordcount, wordcounts)>
	<!ELEMENT rid (#PCDATA)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT rname (#PCDATA)>
	<!ELEMENT region_wordcount (#PCDATA)>
	<!ELEMENT wordcounts (wcentry+)>
	<!ELEMENT wcentry (wc, wcdate, max, min, stddev, average, count)>
	<!ELEMENT wc (#PCDATA)>
	<!ELEMENT wcdate (#PCDATA)>
	<!ELEMENT max (#PCDATA)>
	<!ELEMENT min (#PCDATA)>
	<!ELEMENT stddev (#PCDATA)>
	<!ELEMENT average (#PCDATA)>
	<!ELEMENT count (#PCDATA)>
]>
<wcregionhist>
<rid>190</rid>
<rname>United States :: California :: East Bay</rname>
<region_wordcount>9705674</region_wordcount>
<wordcounts>
<wcentry>
<wc>29694</wc>
<wcdate>2007-11-01</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>329672</wc>
<wcdate>2007-11-02</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>652323</wc>
<wcdate>2007-11-03</wcdate>
<max>28286</max>
<min>0</min>
<stddev>0</stddev>
<average>3048</average>
<count>214</count>
</wcentry>
<wcentry>
<wc>652323</wc>
<wcdate>2007-11-04</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>1225487</wc>
<wcdate>2007-11-05</wcdate>
<max>28286</max>
<min>0</min>
<stddev>0</stddev>
<average>4941</average>
<count>248</count>
</wcentry>
<wcentry>
<wc>1621687</wc>
<wcdate>2007-11-06</wcdate>
<max>28286</max>
<min>0</min>
<stddev>0</stddev>
<average>6006</average>
<count>270</count>
</wcentry>
<wcentry>
<wc>1977910</wc>
<wcdate>2007-11-07</wcdate>
<max>28286</max>
<min>0</min>
<stddev>0</stddev>
<average>6915</average>
<count>286</count>
</wcentry>
<wcentry>
<wc>2285149</wc>
<wcdate>2007-11-08</wcdate>
<max>31746</max>
<min>0</min>
<stddev>0</stddev>
<average>7642</average>
<count>299</count>
</wcentry>
<wcentry>
<wc>2526175</wc>
<wcdate>2007-11-09</wcdate>
<max>35247</max>
<min>0</min>
<stddev>0</stddev>
<average>8337</average>
<count>303</count>
</wcentry>
<wcentry>
<wc>2740473</wc>
<wcdate>2007-11-10</wcdate>
<max>40200</max>
<min>0</min>
<stddev>0</stddev>
<average>8955</average>
<count>306</count>
</wcentry>
<wcentry>
<wc>3052474</wc>
<wcdate>2007-11-11</wcdate>
<max>43786</max>
<min>0</min>
<stddev>0</stddev>
<average>9846</average>
<count>310</count>
</wcentry>
<wcentry>
<wc>3355638</wc>
<wcdate>2007-11-12</wcdate>
<max>48958</max>
<min>0</min>
<stddev>0</stddev>
<average>10720</average>
<count>313</count>
</wcentry>
<wcentry>
<wc>3661951</wc>
<wcdate>2007-11-13</wcdate>
<max>54865</max>
<min>0</min>
<stddev>0</stddev>
<average>11699</average>
<count>313</count>
</wcentry>
<wcentry>
<wc>3898957</wc>
<wcdate>2007-11-14</wcdate>
<max>58208</max>
<min>0</min>
<stddev>0</stddev>
<average>12417</average>
<count>314</count>
</wcentry>
<wcentry>
<wc>4179861</wc>
<wcdate>2007-11-15</wcdate>
<max>62024</max>
<min>0</min>
<stddev>0</stddev>
<average>13311</average>
<count>314</count>
</wcentry>
<wcentry>
<wc>4491931</wc>
<wcdate>2007-11-16</wcdate>
<max>66612</max>
<min>0</min>
<stddev>0</stddev>
<average>14214</average>
<count>316</count>
</wcentry>
<wcentry>
<wc>4767930</wc>
<wcdate>2007-11-17</wcdate>
<max>69714</max>
<min>0</min>
<stddev>0</stddev>
<average>14993</average>
<count>318</count>
</wcentry>
<wcentry>
<wc>5095085</wc>
<wcdate>2007-11-18</wcdate>
<max>72684</max>
<min>0</min>
<stddev>0</stddev>
<average>15922</average>
<count>320</count>
</wcentry>
<wcentry>
<wc>5368533</wc>
<wcdate>2007-11-19</wcdate>
<max>76685</max>
<min>0</min>
<stddev>0</stddev>
<average>16776</average>
<count>320</count>
</wcentry>
<wcentry>
<wc>5697378</wc>
<wcdate>2007-11-20</wcdate>
<max>80011</max>
<min>0</min>
<stddev>0</stddev>
<average>17693</average>
<count>322</count>
</wcentry>
<wcentry>
<wc>5993026</wc>
<wcdate>2007-11-21</wcdate>
<max>83596</max>
<min>0</min>
<stddev>0</stddev>
<average>18554</average>
<count>323</count>
</wcentry>
<wcentry>
<wc>6236320</wc>
<wcdate>2007-11-22</wcdate>
<max>88353</max>
<min>0</min>
<stddev>0</stddev>
<average>19247</average>
<count>324</count>
</wcentry>
<wcentry>
<wc>6437469</wc>
<wcdate>2007-11-23</wcdate>
<max>93768</max>
<min>0</min>
<stddev>0</stddev>
<average>19807</average>
<count>325</count>
</wcentry>
<wcentry>
<wc>6618254</wc>
<wcdate>2007-11-24</wcdate>
<max>96771</max>
<min>0</min>
<stddev>0</stddev>
<average>20363</average>
<count>325</count>
</wcentry>
<wcentry>
<wc>6945847</wc>
<wcdate>2007-11-25</wcdate>
<max>99808</max>
<min>0</min>
<stddev>0</stddev>
<average>21306</average>
<count>326</count>
</wcentry>
<wcentry>
<wc>7357300</wc>
<wcdate>2007-11-26</wcdate>
<max>100792</max>
<min>0</min>
<stddev>0</stddev>
<average>22362</average>
<count>329</count>
</wcentry>
<wcentry>
<wc>7687790</wc>
<wcdate>2007-11-27</wcdate>
<max>104101</max>
<min>0</min>
<stddev>0</stddev>
<average>23367</average>
<count>329</count>
</wcentry>
<wcentry>
<wc>8008051</wc>
<wcdate>2007-11-28</wcdate>
<max>106281</max>
<min>0</min>
<stddev>0</stddev>
<average>24266</average>
<count>330</count>
</wcentry>
<wcentry>
<wc>8386696</wc>
<wcdate>2007-11-29</wcdate>
<max>106281</max>
<min>0</min>
<stddev>0</stddev>
<average>25414</average>
<count>330</count>
</wcentry>
<wcentry>
<wc>9705674</wc>
<wcdate>2007-11-30</wcdate>
<max>128763</max>
<min>0</min>
<stddev>0</stddev>
<average>28800</average>
<count>337</count>
</wcentry>
</wordcounts>
</wcregionhist>
