<?xml version="1.0" standalone="yes"?><!DOCTYPE wcstats [
	<!ELEMENT wcstats (error, site_wordcount, wordcounts)>
	<!ELEMENT error (#PCDATA)>
	<!ELEMENT site_wordcount (#PCDATA)>
	<!ELEMENT wordcounts (wcentry+)>
	<!ELEMENT wcentry (wc, wcdate, max, min, stddev, average, count)>
	<!ELEMENT wc (#PCDATA)>
	<!ELEMENT wcdate (#PCDATA)>
	<!ELEMENT max (#PCDATA)>
	<!ELEMENT min (#PCDATA)>
	<!ELEMENT stddev (#PCDATA)>
	<!ELEMENT average (#PCDATA)>
	<!ELEMENT count (#PCDATA)>
]>
<wcstats>
<site_wordcount>1187931929</site_wordcount>
<wordcounts>
<wcentry>
<wc>6622400</wc>
<wcdate>2007-11-01</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>48976976</wc>
<wcdate>2007-11-02</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>98275963</wc>
<wcdate>2007-11-03</wcdate>
<max>781037</max>
<min>-27</min>
<stddev>6766</stddev>
<average>3211</average>
<count>30603</count>
</wcentry>
<wcentry>
<wc>98275963</wc>
<wcdate>2007-11-04</wcdate>
<max>0</max>
<min>0</min>
<stddev>0</stddev>
<average>0</average>
<count>0</count>
</wcentry>
<wcentry>
<wc>170746440</wc>
<wcdate>2007-11-05</wcdate>
<max>781037</max>
<min>-49999</min>
<stddev>7175</stddev>
<average>4790</average>
<count>35646</count>
</wcentry>
<wcentry>
<wc>217316492</wc>
<wcdate>2007-11-06</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>9303</stddev>
<average>5586</average>
<count>38898</count>
</wcentry>
<wcentry>
<wc>258542475</wc>
<wcdate>2007-11-07</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>10716</stddev>
<average>6315</average>
<count>40939</count>
</wcentry>
<wcentry>
<wc>295066206</wc>
<wcdate>2007-11-08</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>10981</stddev>
<average>6962</average>
<count>42381</count>
</wcentry>
<wcentry>
<wc>329819468</wc>
<wcdate>2007-11-09</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>11283</stddev>
<average>7583</average>
<count>43492</count>
</wcentry>
<wcentry>
<wc>361490331</wc>
<wcdate>2007-11-10</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>12617</stddev>
<average>8173</average>
<count>44225</count>
</wcentry>
<wcentry>
<wc>395578593</wc>
<wcdate>2007-11-11</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>13242</stddev>
<average>8823</average>
<count>44834</count>
</wcentry>
<wcentry>
<wc>434467560</wc>
<wcdate>2007-11-12</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>13880</stddev>
<average>9559</average>
<count>45447</count>
</wcentry>
<wcentry>
<wc>473201894</wc>
<wcdate>2007-11-13</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>14378</stddev>
<average>10273</average>
<count>46060</count>
</wcentry>
<wcentry>
<wc>506204069</wc>
<wcdate>2007-11-14</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>14242</stddev>
<average>10883</average>
<count>46511</count>
</wcentry>
<wcentry>
<wc>539816842</wc>
<wcdate>2007-11-15</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>15479</stddev>
<average>11507</average>
<count>46910</count>
</wcentry>
<wcentry>
<wc>572123401</wc>
<wcdate>2007-11-16</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>15913</stddev>
<average>12106</average>
<count>47258</count>
</wcentry>
<wcentry>
<wc>598012820</wc>
<wcdate>2007-11-17</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>15684</stddev>
<average>12584</average>
<count>47519</count>
</wcentry>
<wcentry>
<wc>629013211</wc>
<wcdate>2007-11-18</wcdate>
<max>999999</max>
<min>-50000</min>
<stddev>16208</stddev>
<average>13177</average>
<count>47734</count>
</wcentry>
<wcentry>
<wc>663688221</wc>
<wcdate>2007-11-19</wcdate>
<max>999999</max>
<min>-92653</min>
<stddev>16844</stddev>
<average>13846</average>
<count>47931</count>
</wcentry>
<wcentry>
<wc>697310090</wc>
<wcdate>2007-11-20</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>17352</stddev>
<average>14481</average>
<count>48151</count>
</wcentry>
<wcentry>
<wc>728478705</wc>
<wcdate>2007-11-21</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>18315</stddev>
<average>15073</average>
<count>48327</count>
</wcentry>
<wcentry>
<wc>756618409</wc>
<wcdate>2007-11-22</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>18714</stddev>
<average>15611</average>
<count>48465</count>
</wcentry>
<wcentry>
<wc>782754010</wc>
<wcdate>2007-11-23</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>19467</stddev>
<average>16113</average>
<count>48578</count>
</wcentry>
<wcentry>
<wc>812911852</wc>
<wcdate>2007-11-24</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>19830</stddev>
<average>16701</average>
<count>48672</count>
</wcentry>
<wcentry>
<wc>850939360</wc>
<wcdate>2007-11-25</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>20690</stddev>
<average>17443</average>
<count>48783</count>
</wcentry>
<wcentry>
<wc>898658932</wc>
<wcdate>2007-11-26</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>21698</stddev>
<average>18364</average>
<count>48935</count>
</wcentry>
<wcentry>
<wc>942127656</wc>
<wcdate>2007-11-27</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>22191</stddev>
<average>19187</average>
<count>49102</count>
</wcentry>
<wcentry>
<wc>986881867</wc>
<wcdate>2007-11-28</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>23052</stddev>
<average>20027</average>
<count>49276</count>
</wcentry>
<wcentry>
<wc>1036369170</wc>
<wcdate>2007-11-29</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>24250</stddev>
<average>20953</average>
<count>49461</count>
</wcentry>
<wcentry>
<wc>1187931929</wc>
<wcdate>2007-11-30</wcdate>
<max>999999</max>
<min>-49999</min>
<stddev>27131</stddev>
<average>23607</average>
<count>50321</count>
</wcentry>
</wordcounts>
</wcstats>
